Settings: Add Show Network Info modal
hsjoberg/blixt-wallet pull request #1078
Opened 2022-11-23 16:43 UTC by niteshbalusu11

Added network info card. 

https://github.com/hsjoberg/blixt-wallet/issues/1064

2022-11-24 23:51 UTC, hsjoberg requested changes
LGTM after some nits 🔥

2022-11-24 23:51 UTC, hsjoberg commented on src/state/Lightning.ts
> +  networkInfo: lnrpc.NetworkInfo;
nit: this either needs to be `networkInfo?: lnrpc.NetworkInfo;` or you have to initialize dummy data.

Seeing how `src/windows/Settings/LightningNetworkInfo.tsx` expects `networkInfo` to possibly be `null`, the former is reasonable  and works like `nodeInfo`.

2022-11-24 23:51 UTC, hsjoberg commented on src/windows/Settings/LightningNetworkInfo.tsx
> +//const { t, i18n } = useTranslation(namespaces.settings.lightningNodeInfo)
Please clear this stuff

2022-11-24 23:51 UTC, hsjoberg commented on src/windows/Settings/LightningNetworkInfo.tsx
> +  t = useTranslation(namespaces.settings.lightningNetworkInfo).t;
Do `const { t } = useTranslation(namespaces.settings.lightningNodeInfo)` instead. Also needs to be in the `MetaData` function above

2022-11-25 01:07 UTC, niteshbalusu11 commented
> LGTM after some nits 🔥

Fixed.

2022-11-25 14:29 UTC, hsjoberg commented
Nice stuff 👍

2022-11-25 14:30 UTC, merged