[HOLD] Newtor foreground services
hsjoberg/blixt-wallet pull request #1123
Opened 2023-01-21 18:28 UTC by djkazic

Not yet ready for merge, but close.

2023-01-21 19:12 UTC, hsjoberg requested changes

2023-01-21 19:12 UTC, hsjoberg commented on src/windows/Settings/Settings.tsx
> +              const torEnabled = useStoreState((store) => store.settings.torEnabled);
Please don't do things with `useStoreState` (or any other hook) inside a closure. It can lead to glitchy behavior. It has to be made in the top-level of a react component. 

You can perhaps move around the code because we actually retrieve `torEnabled` further down

2023-01-21 19:12 UTC, hsjoberg commented on android/app/src/main/java/com/blixtwallet/BlixtTor.java
> +        NotificationChannel channel = new NotificationChannel("com.blixtwallet", "blixt", NotificationManager.IMPORTANCE_NONE);
I think we should get the full application identifier.

Check `LndMobileTools.java`.
I believe it's possible to get the identifier by `BuildConfig.APPLICATION_ID`

2023-01-21 19:12 UTC, hsjoberg commented on android/app/src/main/java/com/blixtwallet/LndMobileScheduledSyncWorker.java
> +        HyperLog.i(TAG, "MainActivity is started, persistentServicesEnabled = " + persistentServicesEnabled + ", quitting job");
nit

```suggestion
        HyperLog.i(TAG, "MainActivity is started or persistentServicesEnabled = " + persistentServicesEnabled + ", quitting job");
```

2023-01-21 19:12 UTC, hsjoberg commented on android/app/src/main/java/com/blixtwallet/LndMobileService.java
> +  private final String CHANNEL_DEFAULT_IMPORTANCE = "blixt";
I don't think this is one is used anywhere

2023-01-22 00:21 UTC, djkazic commented on src/windows/Settings/Settings.tsx
> +              const torEnabled = useStoreState((store) => store.settings.torEnabled);
I have made the call to `NativeModules.BlixtTor.stopTor()` safe to call if Tor is not running. This should work around the need to get `torEnabled` here.

2023-01-22 00:23 UTC, djkazic commented on android/app/src/main/java/com/blixtwallet/LndMobileService.java
> +  private final String CHANNEL_DEFAULT_IMPORTANCE = "blixt";
Fixed.

2023-01-22 00:26 UTC, djkazic commented on android/app/src/main/java/com/blixtwallet/LndMobileScheduledSyncWorker.java
> +        HyperLog.i(TAG, "MainActivity is started, persistentServicesEnabled = " + persistentServicesEnabled + ", quitting job");
Nit fixed.

2023-01-22 00:33 UTC, djkazic commented on android/app/src/main/java/com/blixtwallet/BlixtTor.java
> +        NotificationChannel channel = new NotificationChannel("com.blixtwallet", "blixt", NotificationManager.IMPORTANCE_NONE);
Set `BuildConfig.APPLICATION_ID` in place of `com.blixtwallet`.

2023-01-22 00:37 UTC, djkazic commented on android/app/src/main/java/com/blixtwallet/BlixtTor.java
> +        NotificationChannel channel = new NotificationChannel("com.blixtwallet", "blixt", NotificationManager.IMPORTANCE_NONE);
Fixed this in `LndMobileService` as well.

2023-05-03 20:03 UTC, hsjoberg commented
Work continues in #1188 and `newtor-and-persistent` branch.

2023-05-03 20:03 UTC, closed without merging