Hide forceClosePendingChannel in recovery mode
hsjoberg/blixt-wallet pull request #1124
Opened 2023-01-27 06:57 UTC by niteshbalusu11

Signed-off-by: Nitesh Balusu <niteshbalusu@icloud.com>

Fixes #1111

Hides the button that can forceclose a pending channel when a closing tx id is broadcasted or an SCB restore has been performed.

2023-01-27 20:57 UTC, hsjoberg requested changes
Nice fix! I had no idea `chanStatusFlags` existed.
Please re-work the code a little bit.

2023-01-27 20:57 UTC, hsjoberg commented on src/components/PendingChannelCard.tsx
> +  const CheckForceCloseAbility = () => {
Instead of making a new component and checking the force-closeability inside it, please do it like this:

```
            {isForceClosableChannel && (
              <Row style={{ width: "100%" }}>
                <Left>
                  <Button style={{ marginTop: 14 }} danger={true} small={true} onPress={() => forceClose(channel)}>
                  <Text style={{ fontSize: 8 }}>{t("channel.forceClosePendingChannel")}</Text>
                  </Button>
                </Left>
              </Row>
            )}
```

That way nothing will be rendered if `isForceClosableChannel` is false.

The reason is because making an inline component can have potential performance issues.

2023-01-28 05:12 UTC, niteshbalusu11 commented
Fixed.

2023-01-28 12:02 UTC, hsjoberg commented
LGTM! 🔥

2023-01-28 12:02 UTC, merged