Add fee estimate to payments page
hsjoberg/blixt-wallet pull request #1148
Opened 2023-03-31 16:35 UTC by niteshbalusu11

Closes #1080 

Add fee estimate to payments page.

2023-03-31 16:41 UTC, djkazic approved these changes

2023-04-12 17:42 UTC, hsjoberg requested changes
Looks good! But use the debouncer instead.

2023-04-12 17:42 UTC, hsjoberg commented on src/windows/Send/SendConfirmation.tsx
> +        timeoutId = setTimeout(getFeeEstimate, 1000);
I think this should use the debouncer instead. Check out how it's done in ReceiveSetup.tsx

2023-04-12 19:20 UTC, niteshbalusu11 commented on src/windows/Send/SendConfirmation.tsx
> +        timeoutId = setTimeout(getFeeEstimate, 1000);
Done

2023-04-12 21:49 UTC, niteshbalusu11 commented
Please check now.

2023-04-19 20:22 UTC, hsjoberg approved these changes

2023-04-19 20:22 UTC, merged