Feature: rapid gossip sync
hsjoberg/blixt-wallet pull request #1185
Opened 2023-04-14 20:56 UTC by djkazic

2023-05-05 18:55 UTC, hsjoberg requested changes

2023-05-05 18:55 UTC, hsjoberg commented on android/app/src/main/java/com/blixtwallet/GossipFileScheduledSyncWorker.java
> +  private boolean persistentServicesEnabled = false;
nit: Doesn't really need to global if we exit out early anyway.

2023-05-05 18:55 UTC, hsjoberg commented on android/app/src/main/java/com/blixtwallet/GossipFileScheduledSyncWorker.java
> +          File dgraph = new File("/sdcard/Android/data/com.blixtwallet/cache/dgraph");
Get this path by the Android API (`getCacheDir()` I think) instead of hardcoding.

2023-05-05 18:55 UTC, hsjoberg commented on android/app/src/main/java/com/blixtwallet/GossipFileScheduledSync.java
> +      : new PeriodicWorkRequest.Builder(GossipFileScheduledSyncWorker.class, 3, TimeUnit.HOURS)
Perhaps once per day is more appropriate.

2023-05-05 19:27 UTC, djkazic commented on android/app/src/main/java/com/blixtwallet/GossipFileScheduledSync.java
> +      : new PeriodicWorkRequest.Builder(GossipFileScheduledSyncWorker.class, 3, TimeUnit.HOURS)
OK. I had this set for developing the feature.

2023-05-05 19:30 UTC, djkazic commented on android/app/src/main/java/com/blixtwallet/GossipFileScheduledSyncWorker.java
> +          File dgraph = new File("/sdcard/Android/data/com.blixtwallet/cache/dgraph");
@hsjoberg Yeah I thought about doing that but I wasn't sure where I would grab `context` from. Any ideas?

2023-05-05 19:38 UTC, djkazic commented on android/app/src/main/java/com/blixtwallet/GossipFileScheduledSyncWorker.java
> +          File dgraph = new File("/sdcard/Android/data/com.blixtwallet/cache/dgraph");
Ah it's `getApplicationContext()`

2023-06-21 17:03 UTC, hsjoberg approved these changes
LGTM! 🍰

2023-06-21 17:05 UTC, merged