Add support for fee bumping
hsjoberg/blixt-wallet pull request #1319
Opened 2023-10-27 19:12 UTC by niteshbalusu11

Signed-off-by: Nitesh Balusu <84944042+niteshbalusu11@users.noreply.github.com>

This is still a draft PR, needs some work and on the UI side.

2023-11-01 16:06 UTC, hsjoberg requested changes

2023-11-01 16:06 UTC, hsjoberg commented on src/lndmobile/onchain.ts
> +      toJSON: function (): { [k: string]: any } {
Remove the props that aren't needed

2023-11-01 16:06 UTC, hsjoberg commented on src/components/PendingChannelCard.tsx
> +      feeRate: 100,
Can you add a prompt so the user can set a fee.
We have helper functions for this in `utils/alert.ts`

2023-11-01 16:09 UTC, hsjoberg requested changes
For iOS we need to manually add the gRPC functions in Lnd.swift, otherwise BumpFee won't work.

2023-12-14 18:43 UTC, hsjoberg requested changes

2023-12-14 18:43 UTC, hsjoberg commented on src/windows/LightningInfo/OpenChannel.tsx
> +          type: taprootChan ? lnrpc.CommitmentType["SIMPLE_TAPROOT"] : undefined,
Don't change this

2023-12-14 18:43 UTC, hsjoberg commented on src/components/PendingChannelCard.tsx
> +              index: Number(index),
stylistic: `Number.parseInt()` follows coding conventions in Blixt codebase

2023-12-14 18:43 UTC, hsjoberg commented on src/components/PendingChannelCard.tsx
> +          const feeRateNumber = Number(feeRate);
stylistic: `Number.parseInt()` follows coding conventions in Blixt codebase

2023-12-14 18:43 UTC, hsjoberg commented on src/components/PendingChannelCard.tsx
> +            console.error("Fee bump failed", err);
Can log out error in `Alert.alert` instead

2023-12-14 18:43 UTC, hsjoberg commented on src/lndmobile/onchain.ts
> +    method: "BumpFee",
Name this one `WalletKitBumpFee` as that's the name of the method that Java will automagically find.

2023-12-14 18:43 UTC, hsjoberg commented on ios/LndMobile/Lnd.swift
> +    "BumpFee": { bytes, cb in LndmobileWalletKitBumpFee(bytes, cb) },
`WalletKitBumpFee`

2023-12-14 18:43 UTC, hsjoberg commented on src/components/PendingChannelCard.tsx
> +          const [feeRate, index] = text?.split(":") ?? [];
We don't need split it up because chanpoint already has the index

2023-12-14 18:43 UTC, hsjoberg commented on src/components/PendingChannelCard.tsx
> +                    <Button
Button is misplaced

2023-12-14 18:43 UTC, hsjoberg commented on src/components/PendingChannelCard.tsx
> +                  <Button
note: Not exactly sure how fee bumping would behave under "Waiting for close" state.
Node is trying to negotiate with the peer at this point.

Also, possibly check who the initiator is.

cc @djkazic

2023-12-14 18:43 UTC, hsjoberg commented on src/components/PendingChannelCard.tsx
> +                    <Button
Button misplaced I think.

The fakelnd backend has a channel for all the channel states

2023-12-15 11:25 UTC, niteshbalusu11 commented on src/components/PendingChannelCard.tsx
> +          const [feeRate, index] = text?.split(":") ?? [];
I don't think BumpFee takes the index of the chanpoint, I think it takes the index you want to bump fee using.

2023-12-15 14:56 UTC, hsjoberg requested changes

2023-12-15 14:56 UTC, hsjoberg commented on src/windows/LightningInfo/OpenChannel.tsx
> +      const nodeInfo = await getNodeInfo((peer ?? "").split("@")[0], true);
Can you move this into `state/Channel.ts` instead

2023-12-20 15:25 UTC, hsjoberg approved these changes

2024-01-21 22:19 UTC, merged