I18n
hsjoberg/blixt-wallet pull request #409
Opened 2021-11-24 21:00 UTC by juanAngel

I have implemented an i18n system and refactored the settings window

At the moment there is no language selection button, but it is not complicated to add it

2022-03-15 20:37 UTC, hsjoberg requested changes

2022-03-15 20:37 UTC, hsjoberg commented on locales/en/settings.settings.json
> +    "pingcode":{
pincode instead of pingcode

2022-03-15 20:37 UTC, hsjoberg commented on src/windows/Contacts/ContactList.tsx
> +let t:TFunction;
Is there a reason why this is not inside the component?

2022-03-15 20:37 UTC, hsjoberg commented on src/storage/app.ts
> +    removeItem(StorageItem.name),,
Remove extra ,

2022-03-15 20:37 UTC, hsjoberg commented on src/state/Fiat.ts
> +    } catch (e:any) {
Hmm `:any` should not be needed, we set `useUnknownInCatchVariables` to `false` in `tsconfig.ts`.

https://github.com/hsjoberg/blixt-wallet/blob/c95629fbfaf0ec914e31c771026092a68eaa20ba/tsconfig.json#L13

2022-03-15 20:49 UTC, juanAngel commented on src/windows/Contacts/ContactList.tsx
> +let t:TFunction;
because it is used in several areas of the file

2022-03-26 19:25 UTC, hsjoberg approved these changes

2022-03-26 19:42 UTC, hsjoberg commented
Amazing work @juanAngel. 🎉
LGTM.

2022-03-26 19:43 UTC, merged